headerImage: /assets/img/uploads/l1090396-copy-7.jpg
contactMail: info@team-oberberg.blog
teamInstagram: ssvnuembrecht_einrad
teaserText: >
  An der diesjährigen UNICON 21 - Unicycling Worldchampionships 2024 in Bemidji,
  Minnesota, USA nehmen sechs SportlerInnen aus Oberberg teil. Über unsere
  sportlichen Leistungen und Erlebnisse wollen wir Euch in diesem Blog auf dem
  Laufenden halten.
sponsors:
  - name: INGENIA
    logo: /assets/img/uploads/ingenialogo-nb.png
    url: http://www.dirk-kaiser.de/index.htm
  - name: Tomanek Sicherheitstechnik
    logo: /assets/img/uploads/tomanek-sicherheitstechnik.png
    url: https://team-oberberg.blog/
  - name: Heiner Weiß
    url: https://heiner-weiss.de/
    logo: /assets/img/uploads/heiner-weiß-gmbh-logo-nb.png
  - name: Kaufmann
    logo: /assets/img/uploads/kaufmann-logo_4c_schwarz.png
    url: https://klassikrohbau.de/
  - name: Faulenbach Schmiedetechnik GmbH
    logo: /assets/img/uploads/logo_faulenbach_vektor_4c.svg
    url: https://www.faulenbach-gmbh.de/
  - name: GWN
    logo: /assets/img/uploads/gwn-100-nümbrecht-ohne-hintergrund.png
    url: https://gwn24.de/
  - name: DEVK Michaela Tratz
    logo: /assets/img/uploads/devk-einrad-wm.png
    url: www.michaela-tratz.devk.de
