headerImage: assets/img/uploads/TZ6_9568.jpg
contactMail: "info@team-oberberg.blog"
teaserText: |
  An der diesjährigen UNICON 21 - Unicycling Worldchampionships 2024 in Bemidji, Minnesota, USA nehmen sechs SportlerInnen aus Oberberg teil. Über unsere sportlichen Leistungen und Erlebnisse wollen wir Euch in diesem Blog auf dem Laufenden halten.
