site_url: https://team-oberberg.blog
media_folder: assets/img/uploads

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: "Kontakt"
        name: "contact"
        file: "src/kontakt.md"
        fields:
          - label: "Blog post content"
            name: "body"
            widget: "markdown"
            "editor_components": ["11tyImage"]

      - label: "Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Header Image", name: "headerImage", widget: "image" }
          - { label: "Contact Mail", name: "contactMail", widget: "string" }
          - { label: "Team Instagram", name: "teamInstagram", widget: "string" }
          - { label: "Teaser Text", name: "teaserText", widget: "text" }
          - label: "Sponsors"
            name: "sponsors"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Link", name: "url", widget: "string", optional: true}
          - label: "Wettkämpfe"
            name: "competitions"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Kategorie", name: "category", widget: "string"}
              - {label: "Datum" , name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Vorschau", name: "abstract", widget: "string" }
      - label: "Cover"
        name: "cover"
        widget: "image"
        allow_multiple: false

      - label: "Blog post content"
        name: "body"
        widget: "markdown"
        "editor_components": ["11tyImage"]

  - name: "events"
    label: "Events"
    folder: "src/events"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false

      - label: "Anzeige Datum überschreiben"
        name: "displayDate"
        widget: "string"
        optional: true

      - { label: "Unveröffentlicht", name: "unpublished", widget: "boolean" }
      - label: "Cover"
        name: "cover"
        widget: "image"
        allow_multiple: false
        optional: true

      - label: "Blog post content"
        name: "body"
        widget: "markdown"
        "editor_components": ["11tyImage"]

  - name: "fahrer"
    label: "Fahrer"
    folder: "src/fahrer"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Startnummer", name: "startNo", widget: "number" }
      - { label: "Zitat", name: "cite", required: false, widget: "string" }
      - label: "Geburtstag"
        name: "birthday"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
      - { label: "WM#", name: "wm", widget: "number" }
      - label: "Top 3 Plätze im letzten Jahr"
        name: "top3since2022"
        widget: "hidden"
        required: false
      - { label: "Top 10 Plätze in WMs", name: "top10inWM", widget: "hidden", required: false }
      - { label: "Mein größter Erfolg", name: "biggestAchievement", widget: "string", required: false }
      - label: "Bild - nur mit transparentem Hintergrund"
        name: "image"
        widget: "image"
        choose_url: false
        allow_multiple: false
      - label: Teams
        name: teams
        widget: select
        multiple: true
        options:
          - "SSV Nümbrecht"
          - "RKB Freestyle Team"
          - "TuS Reichshof - All Stars On(e) Wheel"
          - SSF Bonn
      - label: Wettkämpfe
        name: competitions
        widget: select
        multiple: true
        options:
          - 50m Einbein
          - 100m
          - 400m
          - 800m
          - 10K
          - 4x100m Staffel
          - Coasting
          - Convention Contest (Individual / Pair U15)
          - Convention Contest (Individual 15+)
          - Convention contest (Pairs 15+)
          - Criterium
          - Cross Country (Beginner)
          - Cross Country (Expert)
          - Cyclocross
          - Downhill Beginner
          - Downhill Expert
          - Flat
          - Flatland
          - Flatland (Expert)
          - Flatland (Junior)
          - Freestyle
          - Groups
          - IUF Slalom
          - Individual Expert
          - Individual Junior Expert
          - Jumps on Platform
          - Jumps on Track
          - Marathon (42k)
          - Muni
          - Pairs Junior Expert / Expert
          - Speed Trial
          - Stillstand
          - Street
          - Trial
          - Uphill Beginner
          - Uphill Expert
          - WW
          - X-Style

local_backend: true
backend:
  name: git-gateway
  branch: main
